const token=localStorage.getItem("grille_admin_token");if(!token && !location.pathname.includes("login"))location.href="/admin/login.html";
async function adminApi(url,opts={}){const r=await fetch(url,{...opts,headers:{"Content-Type":"application/json","Authorization":"Bearer "+token,...(opts.headers||{})}});if(r.status===401){localStorage.removeItem("grille_admin_token");location.href="/admin/login.html"}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Error");return d}
function stat(label,value){return `<div class="stat"><span>${label}</span><strong>${value}</strong></div>`}
async function loadDashboard(){const d=await adminApi("/api/admin/dashboard");document.querySelector("#stats").innerHTML=stat("Ventas de hoy",money(d.salesToday))+stat("Pedidos hoy",d.ordersToday)+stat("Ticket promedio",money(d.averageTicket))+stat("Pedidos pendientes",d.pendingOrders);document.querySelector("#recent").innerHTML=tableOrders(d.recentOrders)}
function tableOrders(orders){return `<table class="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Total</th><th>Pago</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer.name}</td><td>${money(o.total)}</td><td>${o.paymentMethod}</td><td>${o.status}</td><td><select onchange="changeOrder('${o.id}',this.value)"><option value="">Cambiar</option><option value="confirmed">Confirmado</option><option value="preparing">En preparación</option><option value="ready">Listo</option><option value="sent">Enviado</option><option value="delivered">Entregado</option><option value="cancelled">Cancelado</option></select></td></tr>`).join("")}</tbody></table>`}
async function loadOrders(){const o=await adminApi("/api/admin/orders");document.querySelector("#orders").innerHTML=tableOrders(o)}
async function changeOrder(id,status){if(!status)return;await adminApi("/api/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status})});if(document.querySelector("#orders"))loadOrders();else loadDashboard()}
async function loadProducts(){const p=await adminApi("/api/admin/products");document.querySelector("#productsAdmin").innerHTML=`<table class="table"><thead><tr><th>Nombre</th><th>Precio</th><th>Categoría</th><th>Disponible</th><th>Acción</th></tr></thead><tbody>${p.map(x=>`<tr><td>${x.name}</td><td>${money(x.price)}</td><td>${x.categoryId}</td><td>${x.available?"Sí":"No"}</td><td><button class="linkbtn" onclick="deleteProduct('${x.id}')">Eliminar</button></td></tr>`).join("")}</tbody></table>`;const f=document.querySelector("#productForm");if(f)f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f).entries());await adminApi("/api/admin/products",{method:"POST",body:JSON.stringify(d)});f.reset();loadProducts()}}
async function deleteProduct(id){if(confirm("¿Eliminar producto?")){await adminApi("/api/admin/products/"+id,{method:"DELETE"});loadProducts()}}
async function loadSales(){const d=await adminApi("/api/admin/stats");document.querySelector("#sales").innerHTML=stat("Ventas acumuladas",money(d.totalSales))+stat("Pedidos",d.totalOrders);document.querySelector("#best").innerHTML="<h2>Productos más vendidos</h2>"+Object.entries(d.bestSellers).sort((a,b)=>b[1]-a[1]).map(x=>`<p>${x[0]} — <b>${x[1]}</b> unidades</p>`).join("")}
document.querySelector("#logout")?.addEventListener("click",()=>{localStorage.removeItem("grille_admin_token");location.href="/admin/login.html"});
if(location.pathname==="/admin/"||location.pathname==="/admin/index.html")loadDashboard();